#!/usr/bin/perl
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Generate CodeSamples/snippets.d
#
# Note: Output file name is specified in gen_snippet_d.sh
#
# Copyright (C) Akira Yokosawa, 2018
#
# Authors: Akira Yokosawa <akiyks@gmail.com>

use strict;
use warnings;

my @fcvsources;
my @fcvsources_ltms;
my $snippet_key;
my $snippet_key_ltms;
my $source;

$snippet_key = '\begin{snippet}' ;
$snippet_key_ltms = '\begin[snippet]' ;
@fcvsources = `grep -l -r -F '$snippet_key' CodeSamples` ;
@fcvsources_ltms = `grep -l -r -F '$snippet_key_ltms' CodeSamples` ;
chomp @fcvsources ;
chomp @fcvsources_ltms ;

print "# Do not edit!\n" ;
print "# Generated by utilities/gen_snippet_d.pl.\n\n" ;
print "FCVSNIPPETS = " ;
foreach $source (@fcvsources) {
    my @snippet_commands1 ;
    my $subdir ;
    my $snippet ;
    if ($source =~ /\.ltms$/) {
	next;
    }
    @snippet_commands1 = `grep -F '$snippet_key' $source` ;
    chomp @snippet_commands1 ;
    $source =~ m!(.*/[^/]+)/[^/]+! ;
    $subdir = $1 ;
    foreach $snippet (@snippet_commands1) {
	$snippet =~ /labelbase=.*:(.+:[^,\]]+)[,\]]/ ;
	$_ = $1;
	s/:/@/g ;
	print "\\\n\t$subdir/$_.fcv ";
    }
}
print "\nFCVSNIPPETS_VIA_LTMS = " ;
foreach $source (@fcvsources_ltms) {
    my @snippet_commands1 ;
    my $subdir ;
    my $snippet ;
    @snippet_commands1 = `grep -F '$snippet_key_ltms' $source` ;
    chomp @snippet_commands1 ;
    $source =~ m!(.*/[^/]+)/[^/]+! ;
    $subdir = $1 ;
    foreach $snippet (@snippet_commands1) {
	$snippet =~ /labelbase=.*:(.+:[^,\]]+)[,\]]/ ;
	$_ = $1;
	s/:/@/g ;
	print "\\\n\t$subdir/$_.fcv ";
    }
}
print "\nFCVSNIPPETS_LTMS = " ;
foreach $source (@fcvsources_ltms) {
    $_ = $source ;
    s/\.litmus$/\.ltms/ ;
    print "\\\n\t$_";
}

print "\n\nEXTRACT = utilities/fcvextract.pl\n" ;
print "REORDER_LTMS = utilities/reorder_ltms.pl\n\n" ;

foreach $source (@fcvsources) {
    my @snippet_commands2 ;
    my $src_under_sub ;
    my $subdir ;
    my $snippet ;
    if ($source =~ /\.ltms$/) {
	next;
    }
    @snippet_commands2 = `grep -F '$snippet_key' $source` ;
    chomp @snippet_commands2 ;
    $src_under_sub = $source ;
    $source =~ m!(.*/[^/]+)/[^/]+! ;
    $subdir = $1 ;
#    print @snippet_commands ;
    foreach $snippet (@snippet_commands2) {
	$snippet =~ /labelbase=.*:(.+:[^,\]]+)[,\]]/ ;
	if (not defined $1) {
	    die("Oops! Please try \"make clean; make\".\n") ;
	}
	$_ = $1;
	s/:/@/g ;
	print "$subdir/$_.fcv: $src_under_sub \$\(EXTRACT\)\n";
    }
}
foreach $source (@fcvsources_ltms) {
    my @snippet_commands2 ;
    my $src_under_sub ;
    my $subdir ;
    my $snippet ;
    @snippet_commands2 = `grep -F '$snippet_key_ltms' $source` ;
    chomp @snippet_commands2 ;
    $src_under_sub = $source ;
    $source =~ m!(.*/[^/]+)/[^/]+! ;
    $subdir = $1 ;
#    print @snippet_commands ;
    foreach $snippet (@snippet_commands2) {
	$_ = $src_under_sub ;
	s/\.litmus$// ;
	$src_under_sub = $_ ;
	print "$src_under_sub.ltms: $src_under_sub.litmus \$\(REORDER_LTMS\)\n" ;
	$snippet =~ /labelbase=.*:(.+:[^,\]]+)[,\]]/ ;
	if (not defined $1) {
	    die("Oops! Please try \"make clean; make\".\n") ;
	}
	$_ = $1;
	s/:/@/g ;
	print "$subdir/$_.fcv: $src_under_sub.ltms \$\(EXTRACT\)\n";
    }
}
