image: archlinux:latest

stages:
  - test
  - build

test_codesamples:
    tags: [ saas-linux-medium-amd64 ]
    stage: test

    before_script:
        - pacman --noconfirm -Syu make gcc liburcu

    script:
        - make -C CodeSamples/
        - make -C CodeSamples/ check

generate_pdfs:
    stage: build

    before_script:
        - pacman --noconfirm -Syu texlive-meta fig2dev ghostscript graphviz librsvg gnuplot wget make which fontconfig git ttf-dejavu gnu-free-fonts ttf-liberation
        - mkdir -p ~/.local/share/fonts && cp fonts/steel-city-comic.regular.ttf ~/.local/share/fonts/ && fc-cache

    script:
        - source /etc/profile
        - make perfbook.pdf perfbook-1c.pdf perfbook-eb.pdf

    artifacts:
      paths:
          - perfbook.pdf
          - perfbook-1c.pdf
          - perfbook-eb.pdf
