#!/bin/sh

awk '	{
	if ($0 == "%%BoundingBox: 50 50 302 410") {
		print "%%BoundingBox: 50 50 302 300"
	} else if ($1 == "%%Title:") {
		print "%%Title: Is Parallel Programming Hard, And, If So, What Can You Do About It?"
	} else if ($1 == "/Title") {
		print "  /Title (Is Parallel Programming Hard, And, If So, What Can You Do About It?)"
	} else {
		print $0
	}
	}' | sed -e 's/^(19/(/' -e 's/^(20/(/'
